remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Azure Snippets]
description: [Built to provide Snippets for  making life easier on Azure]
show_downloads: [false]
cayman:
  show_downloads_subpages: false
google_analytics: [G-BC38MDLP6H]